"""
Tool: thinkneo_business_impact
Executive dashboard: total value generated, total AI cost, ROI, risk avoided, and cost-per-decision —
all in one view. The CxO report.
Requires authentication.
"""
from __future__ import annotations

import json
from typing import Annotated

from mcp.server.fastmcp import FastMCP
from mcp.types import ToolAnnotations
from pydantic import Field

from ..auth import require_auth
from ..database import hash_key, _get_conn
from ._common import utcnow, validate_workspace


def register(mcp: FastMCP) -> None:
    @mcp.tool(
        name="thinkneo_business_impact",
        description=(
            "Executive business impact dashboard. Returns a single view of: "
            "total value generated by AI agents, total AI cost, net ROI, risk avoided in dollars, "
            "cost per decision, top performing agents, and risk event summary. "
            "This is the report a CxO needs to justify AI investment."
        ),
        annotations=ToolAnnotations(readOnlyHint=True, idempotentHint=True),
    )
    def thinkneo_business_impact(
        workspace: Annotated[str, Field(description="Workspace identifier")] = "default",
        period: Annotated[str, Field(description="Time period: 'this-week', 'this-month', 'this-quarter', 'all'")] = "this-month",
    ) -> str:
        token = require_auth()
        key_h = hash_key(token)
        validate_workspace(workspace)

        period_sql = {
            "this-week": "AND day >= date_trunc('week', CURRENT_DATE)",
            "this-month": "AND day >= date_trunc('month', CURRENT_DATE)",
            "this-quarter": "AND day >= date_trunc('quarter', CURRENT_DATE)",
            "all": "",
        }.get(period, "AND day >= date_trunc('month', CURRENT_DATE)")

        risk_period_sql = period_sql.replace("day", "blocked_at")
        decision_period_sql = period_sql.replace("day", "decided_at")

        try:
            conn = _get_conn()

            # Aggregate totals
            with conn.cursor() as cur:
                cur.execute(f"""
                    SELECT
                        COALESCE(SUM(total_decisions), 0) as decisions,
                        COALESCE(SUM(successful_decisions), 0) as successful,
                        ROUND(COALESCE(SUM(total_ai_cost_usd), 0)::numeric, 4) as total_cost,
                        ROUND(COALESCE(SUM(total_value_generated_usd), 0)::numeric, 2) as total_value,
                        ROUND(COALESCE(SUM(total_risk_avoided_usd), 0)::numeric, 2) as risk_avoided,
                        COUNT(DISTINCT agent_name) as agent_count
                    FROM agent_value_daily
                    WHERE key_hash = %s AND workspace = %s {period_sql}
                """, (key_h, workspace))
                totals = cur.fetchone()

            # Top agents by value
            with conn.cursor() as cur:
                cur.execute(f"""
                    SELECT agent_name,
                        SUM(total_decisions) as decisions,
                        ROUND(SUM(total_ai_cost_usd)::numeric, 4) as cost,
                        ROUND(SUM(total_value_generated_usd)::numeric, 2) as value,
                        ROUND(SUM(total_risk_avoided_usd)::numeric, 2) as risk
                    FROM agent_value_daily
                    WHERE key_hash = %s AND workspace = %s {period_sql}
                    GROUP BY agent_name
                    ORDER BY value DESC
                    LIMIT 10
                """, (key_h, workspace))
                top_agents = [
                    {
                        "agent": r["agent_name"],
                        "decisions": r["decisions"],
                        "ai_cost_usd": float(r["cost"] or 0),
                        "value_usd": float(r["value"] or 0),
                        "risk_avoided_usd": float(r["risk"] or 0),
                        "roi": f"{round((float(r['value'] or 0) + float(r['risk'] or 0)) / float(r['cost']), 1)}:1" if float(r["cost"] or 0) > 0 else "infinite",
                    }
                    for r in cur.fetchall()
                ]

            # Risk summary
            with conn.cursor() as cur:
                cur.execute(f"""
                    SELECT risk_type, severity, COUNT(*) as events,
                        ROUND(SUM(estimated_impact_usd)::numeric, 2) as total_impact
                    FROM risk_events
                    WHERE key_hash = %s AND workspace = %s {risk_period_sql}
                    GROUP BY risk_type, severity
                    ORDER BY total_impact DESC
                    LIMIT 10
                """, (key_h, workspace))
                risk_summary = [
                    {"type": r["risk_type"], "severity": r["severity"],
                     "events": r["events"], "impact_avoided_usd": float(r["total_impact"] or 0)}
                    for r in cur.fetchall()
                ]

            # Process efficiency (baselines vs actual)
            with conn.cursor() as cur:
                cur.execute(f"""
                    SELECT d.process_name,
                        b.cost_per_unit_usd as baseline_cost,
                        b.unit_label,
                        COUNT(*) as ai_decisions,
                        ROUND(AVG(d.ai_cost_usd)::numeric, 6) as avg_ai_cost,
                        ROUND(SUM(d.value_generated_usd)::numeric, 2) as total_value_captured
                    FROM decisions d
                    JOIN value_baselines b ON b.key_hash = d.key_hash AND b.workspace = d.workspace AND b.process_name = d.process_name
                    WHERE d.key_hash = %s AND d.workspace = %s {decision_period_sql}
                    GROUP BY d.process_name, b.cost_per_unit_usd, b.unit_label
                    ORDER BY total_value_captured DESC
                    LIMIT 10
                """, (key_h, workspace))
                processes = [
                    {
                        "process": r["process_name"],
                        "baseline_cost_per_unit": float(r["baseline_cost"]),
                        "unit": r["unit_label"],
                        "ai_decisions": r["ai_decisions"],
                        "avg_ai_cost_per_decision": float(r["avg_ai_cost"] or 0),
                        "cost_reduction_pct": round((1 - float(r["avg_ai_cost"] or 0) / float(r["baseline_cost"])) * 100, 1) if float(r["baseline_cost"]) > 0 else 0,
                        "total_value_captured_usd": float(r["total_value_captured"] or 0),
                    }
                    for r in cur.fetchall()
                ]

            conn.close()

            total_cost = float(totals["total_cost"] or 0)
            total_value = float(totals["total_value"] or 0)
            risk_avoided = float(totals["risk_avoided"] or 0)
            total_impact = total_value + risk_avoided
            decisions = totals["decisions"] or 0

            return json.dumps({
                "report": "ThinkNEO Business Impact",
                "period": period,
                "workspace": workspace,
                "summary": {
                    "total_ai_investment_usd": total_cost,
                    "total_value_generated_usd": total_value,
                    "total_risk_avoided_usd": risk_avoided,
                    "total_business_impact_usd": round(total_impact, 2),
                    "net_roi": f"{round(total_impact / total_cost, 1)}:1" if total_cost > 0 else "no_cost_recorded",
                    "total_decisions": decisions,
                    "avg_cost_per_decision_usd": round(total_cost / decisions, 6) if decisions > 0 else 0,
                    "success_rate_pct": round(float(totals["successful"] or 0) / decisions * 100, 1) if decisions > 0 else 0,
                    "active_agents": totals["agent_count"],
                },
                "top_agents": top_agents,
                "process_efficiency": processes,
                "risk_events": risk_summary,
                "generated_at": utcnow(),
            }, indent=2)
        except Exception as e:
            return json.dumps({"error": str(e), "generated_at": utcnow()}, indent=2)
